### ISSUE TITLE
Doesn't compile with msvc 16.10

### ISSUE THREAD

**Issue by s9w** [marzer/tomlplusplus#95]
## Environment
**toml++ version and/or commit hash:**   2.3.0
**Compiler:**   msvc 16.10.0 preview 2.0
**C++ standard mode (e.g. 17, 20, 'latest'):**   20
**Target arch (e.g. x64):**   x64

## Describe the bug
Doesn't compile, i.e. `toml_parser.hpp(478,41): error C7595: 'toml::v2::operator ""_sz': call to immediate function is not a constant expression`. Problem is this line:
```
void stop_recording(size_t pop_bytes = 0_sz) noexcept
```
Not sure if he's right, I didn't play around with consteval yet. I can say that is no problem on my 16.4 msvc. So somewhere in between, something broke.

## Steps to reproduce (or a small repro code sample)
`#include <toml++/toml.h>` is enough.

**Comment by marzer** [comment]
Seems like a duplicate of https://github.com/marzer/tomlplusplus/issues/93, which is fixed in `master`. Try grabbing the latest commit and see how you go.

**Comment by s9w** [comment]
Yes, that other was closed already that's why I didn't see it. Sorry & thanks, seems to have been taken care of

**Comment by marzer** [comment]
No worries, happy to help.
